In [1]:
import numpy as np
import pandas as pd


In [3]:
df=pd.read_csv("datasets/customer.csv")

In [4]:
df.sample(5)

age  gender   review education purchased
37   94    Male  Average        PG       Yes
49   25  Female     Good        UG        No
29   83  Female  Average        UG       Yes
34   86    Male  Average    School        No
42   30  Female     Good        PG       Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [6]:
df.shape

(50, 5)

In [7]:
df.describe()

age
count  50.000000
mean   54.160000
std    25.658161
min    15.000000
25%    30.250000
50%    57.000000
75%    74.000000
max    98.000000

In [9]:
df["purchased"].value_counts()

No     26
Yes    24
Name: purchased, dtype: int64

In [10]:
df.isnull().sum()

age          0
gender       0
review       0
education    0
purchased    0
dtype: int64

In [11]:
df.duplicated().sum()

1

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.shape

(49, 5)

In [17]:
df.corr()

age
age  1.0

In [18]:
df.sample(5)

age  gender   review education purchased
24   16  Female  Average        PG       Yes
37   94    Male  Average        PG       Yes
41   23    Male     Good        PG       Yes
26   53  Female     Poor        PG        No
2    70  Female     Good        PG        No

In the above dataframe, as we can see that, gender is nominal column so we will be applying one-hot-coding on the gender."review" and "education" is the ordinal column, so we will be applying ordinal_encoding on this column. "purchased" column is the output column, so we will be applying the label encoding on the "Purchased" column.

For this sheet, we will be first apply the ordinal encoding on the "review" and "education" column and label encoding on the "purchased" column.


In [20]:
df=df.iloc[:,2:]

In [21]:
df.head(3)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No

In [22]:
from sklearn.model_selection import train_test_split

In [28]:
#df.iloc[:,2:3]

In [29]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:2],df.iloc[:,2:3])

In [30]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((36, 2), (13, 2), (36, 1), (13, 1))

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [33]:
X_train["review"].value_counts()

Average    12
Good       12
Poor       12
Name: review, dtype: int64

In [34]:
X_train["education"].value_counts()

School    13
UG        12
PG        11
Name: education, dtype: int64

In [35]:
oe=OrdinalEncoder(categories=[["Poor","Good","Average"],["School","UG","PG"]])


In [36]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Good', 'Average'], ['School', 'UG', 'PG']])

In [38]:
oe.transform(X_train)
oe.transform(X_test)

array([[0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.]])

In [41]:
oe.categories_

[array(['Poor', 'Good', 'Average'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
le=LabelEncoder()

In [45]:
le.fit(y_train)

/home/ajit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [46]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [47]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

/home/ajit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:
y_train

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0])

In [49]:
y_test

array([1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1])